version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rest-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mcvhaloac54c"
s3_prefix = "rest-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
